### ISSUE TITLE
`postgresql_extension` doesn't allow to select the database

### ISSUE THREAD

**Issue by multani** [edgelaboratories/terraform-provider-postgresql#3]
The extension is created with the database used by the provider.

It would be better to allow the creation with a specific database name.

**Comment by cyrilgdn** [comment]
Fixed by #9  which has been merged in [internal-release](https://github.com/edgelaboratories/terraform-provider-postgresql/tree/internal-release)

The PR is still open because test are not ok. Deletion of a postgresql_role can fail (and fails in the tests) if it still owns objects which are not in the current database during deletion (the database configured in the provider).
